/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xC9, 0xD4, 0x38, 0x79, 0x25, 0x61, 0x35, 0x00}
#define VIAL_COMBO_ENTRIES 64
#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#define TAPPING_TERM 250

#define RGB_DI_PIN WS2812_DI_PIN

#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_CYCLE_ALL
#define RGB_MATRIX_STARTUP_HUE RGB_MATRIX_DEFAULT_HUE
#define RGB_MATRIX_STARTUP_SAT RGB_MATRIX_DEFAULT_SAT
#define RGB_MATRIX_STARTUP_VAL RGB_MATRIX_DEFAULT_VAL
#define RGB_MATRIX_STARTUP_SPD RGB_MATRIX_DEFAULT_SPD
